In [2]:
!pip install numpy

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [4]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
print(np.arange(4))
print(np.arange(0, 10, 2))

[0 1 2 3]
[0 2 4 6 8]


In [11]:
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

# Append

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.append(arr, [1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

# Delete

In [14]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

# Sort

In [15]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
array_example = np.array([[[0, 1, 2, 3],
                                      [4, 5, 6, 7]],
                                      
                                      [[0, 1, 2, 3],
                                      [4, 5, 6, 7]],
                                      
                                      [[0, 1, 2, 3],
                                      [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [22]:
# mengetahui jumlah axes atau dimensi array
array_example.ndim

3

In [21]:
# mengetahui jumlah total elemen array
array_example.size

24

In [23]:
# menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan sepanjang setiap dimensi array
array_example.shape

(3, 2, 4)

In [25]:
arr_one = np.array([[1, 2, 3, 4, 5]])
arr_one.ndim

2

In [26]:
arr_one.size

5

In [27]:
arr_one.shape

(1, 5)

# np.shape
memberi bentuk baru array tanpa mengubah datanya

In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
b = a.reshape(3, 2) #3 baris 2 kolom
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [30]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [32]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [33]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [37]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [38]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and Slicing

In [39]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [42]:
five_up = (a>=5)
print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [43]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [44]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

## vstack
menumpuk array secara vertical

In [6]:
a_1 = np.array([[1, 1], [2, 2]])
a_2 = np.array([[3, 3], [4, 4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

## hstack
membagi array menjadi beberapa array yang lebih kecil

In [7]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [9]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [10]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [15]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [16]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [17]:
#menjumlahkan baris
b.sum(axis=0)

array([3, 3])

In [18]:
#menjumlahkan kolom
b.sum(axis=1)

array([2, 4])

In [19]:
data = np.array([1, 2])
data

array([1, 2])

In [21]:
ones = np.ones(2)
ones

array([1., 1.])

In [22]:
data + ones

array([2., 3.])

In [23]:
data*data

array([1, 4])

In [24]:
data/data

array([1., 1.])

# Broadcasting

In [25]:
data*2

array([2, 4])

# More Array Operations

In [26]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
             [0.54627315, 0.05093587, 0.40067661, 0.55645992],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645992]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [27]:
A. sum()

4.85957839

In [28]:
A.min()

0.05093587

In [29]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [31]:
A.max()

0.82485143

In [32]:
A.max(axis=1)

array([0.5510652 , 0.55645992, 0.82485143])

In [33]:
A.std() #menentukan standard deviation

0.21392120707074483

# Matrices

In [34]:
np.ones((3, 2))
np.zeros((3, 2))
np.random.random((3, 2))

print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(np.random.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.48014026 0.87740131]
 [0.10317867 0.08525   ]
 [0.35500494 0.05071229]]


## Matrix Arithmetic

In [35]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [36]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [37]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [38]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [39]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [40]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [41]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [44]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [45]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [46]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [47]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [48]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [50]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [51]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [55]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5,6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [59]:
print(np.zeros((4, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [60]:
print(np.random.random((4, 3, 2)))

[[[0.79561439 0.7783743 ]
  [0.67376187 0.39320517]
  [0.48457802 0.00300518]]

 [[0.85789362 0.33551187]
  [0.26013247 0.33548919]
  [0.76290402 0.94169811]]

 [[0.97224449 0.17091375]
  [0.97492813 0.07483644]
  [0.17990052 0.0040759 ]]

 [[0.14358446 0.1774221 ]
  [0.44599851 0.33679636]
  [0.91606559 0.75728963]]]


# Flatten N-Dimensional Array

In [61]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])